[tool.poetry]
name = "bilireq"
version = "0.1.1"
description = ""
authors = ["SK-415 <2967923486@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.22.0"
qrcode = {extras = ["pil"], version = "^7.3.1"}
rsa = "^4.8"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"

[tool.poetry.extras]
qrcode = ["qrcode"]

# [[tool.poetry.source]]
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
